language: node_js
node_js:
  - node
cache: npm

env:
  global:
    - NODE_ENV=test
    - GITHUB_REPO="devdbrandy/minimalistic-microservice"

after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
